name: C/C++ CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build_xp:
    name: Windows XP
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/setup-nasm@v1
      - uses: shogo82148/actions-setup-perl@v1

      - name: Install VS2017 XP tools
        shell: powershell
        run: |
          if (-not (Test-Path "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise")) {
              Invoke-WebRequest -Uri "https://aka.ms/vs/15/release/vs_buildtools.exe" -OutFile "$env:RUNNER_TEMP\vs_buildtools.exe"
              Start-Process -Wait -FilePath "$env:RUNNER_TEMP\vs_buildtools.exe" -ArgumentList @(
                  "--quiet", "--wait", "--norestart", "--nocache",
                  "--add Microsoft.VisualStudio.Workload.VCTools",
                  "--add Microsoft.VisualStudio.Component.VC.v141.x86.x64",
                  "--add Microsoft.VisualStudio.Component.Windows10SDK.17134",
                  "--add Microsoft.VisualStudio.Component.VC.ATL",
                  "--add Microsoft.VisualStudio.ComponentGroup.NativeDesktop.WinXP"
              )
          }

      - name: Set up Visual Studio (Win32)
        uses: egor-tensin/vs-shell@v2
        with:
          arch: Win32

      - name: Build DotAAllstarsHelper (XP)
        run: |
          msbuild DotAAllstarsHelper.sln `
            /p:Configuration=Release `
            /p:Platform=Win32 `
            /p:PlatformToolset=v141_xp `
            /p:WindowsTargetPlatformVersion=7.1A `
            /p:VisualStudioVersion=15.0

      - name: Sign binaries
        run: |
          ./SignRelease.bat

      - name: Create ZIP (Store method - no compression)
        run: |
          7z a -mx=1 DotAAllstarsHelper.zip Release/DotAAllstarsHelperFinal.dll Release/DotAAllstarsHelperFinal.pdb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DotAAllstarsHelper
          path: DotAAllstarsHelper.zip

  package:
    name: Create Release
    runs-on: windows-latest
    needs: [build_xp]
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: DotAAllstarsHelper
          path: .

      - name: Delete temp artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: DotAAllstarsHelper

      - name: Tag version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          files: |
            DotAAllstarsHelper.zip
